### ISSUE TITLE
training on  one GPU

### ISSUE THREAD

**Issue by yaolugithub** [XuecaiHu/Meta-SR-Pytorch#10]
Hi, Xuecai.

Thanks for your wonderful work about arbitrary upscale factor of SR.
What i want to know is that if i only have one GPU, what should i need to modify the code? 
Besides, could you tell me how long is the training process?

Thanks a lot.

**Comment by XuecaiHu** [comment]
Yes you can, change the nGPUs as  1.  But it is best to use a smaller network to test our methods (such as SRResNet or edsr_baseline (you can go to https://github.com/thstkdgus35/EDSR-PyTorch)), and reduce the hidden neuron from 256 to 128.  It will cost about 2 days to train our Meta-SR. Training on the RDN and RCAN (which is too big) will cost a week more. So I really donot recommend to use RDN or RCAN as backbone.  Both the RDN and RCAN is too big and very time-consuming.

**Comment by yaolugithub** [comment]
Thank you very much for your patient reply. Good luck with your work

Best regards,
Luyao

XuecaiHu <notifications@github.com> 于2019年6月26日周三 下午4:20写道：
