### ISSUE TITLE
An implementation for prepare_dataset with parfor in parallel

### ISSUE THREAD

**Issue by idealboy** [XuecaiHu/Meta-SR-Pytorch#13]
I have an parallel version implemented by parfor:

https://github.com/idealboy/Meta-SR-Pytorch/blob/master/prepare_dataset/generate_LR_metasr_X1_X4_mt.m

But I have no the permission to upload the *.m into this branch.

**Comment by XuecaiHu** [comment]
you can use the pull request, then i will pass you request

**Comment by XuecaiHu** [comment]
I have added your matlab code.
