### ISSUE TITLE
training with 1x256x256 images

### ISSUE THREAD

**Issue by pancakewaffles** [XuecaiHu/Meta-SR-Pytorch#18]
Hi Xuecai,

Are there any issues with using this on 1x256x256 images (with n_colours = 1 instead of 3)? Are there any parameters that should be tweaked or modified to accommodate that n_colours =1? I ran into this issue and I am not sure where to start looking to debug this.

     79     output = torch.masked_select(output,mask)
---> 80     output = output.contiguous().view(N,C,outH,outW)
     81     loss = criterion(output,target)
     82 

RuntimeError: shape '[2, 1, 256, 256]' is invalid for input of size 393216

Here batch size is 2, n_colours = out_channels = 1, and the HR image size is 256x256

**Comment by PSZehnder** [comment]
@pancakewaffles did you find a solution to this?
