### ISSUE TITLE
how to continue training from a specific checkpoint

### ISSUE THREAD

**Issue by asiandragon** [XuecaiHu/Meta-SR-Pytorch#19]
Hi,

Thanks for sharing your code.
The training phase needs 1000 epochs.
If I stop the training at the 500 epoch, how to load the model and continue the training?
Just set args.resume=500? Whether need to change the parameter args.start_epoch?

Thank you.

**Comment by XuecaiHu** [comment]
--pre_train  and --start_epoch. We donot use the resume.

**Comment by asiandragon** [comment]
Thanks for your reply!
