### ISSUE TITLE
questions about model input and output

### ISSUE THREAD

**Issue by yfzcopy0702** [XuecaiHu/Meta-SR-Pytorch#2]
Hi, Xuecai,

I noticed that in your code, the metardn model takes "pos_mat" as input and the shape of output is [N, outC, scale_int×inH, scale_int×inW], where scale_int = math.ceil(scale). And then after model output,  you have an extra step of torch.masked_select to get the final output with shape [N, outC, int(scale×inH), int(scale×inW)].

I wonder why you don't input the "pos_mat" with the right shape, and directly get the final output with shape [N, outC, int(scale×inH), int(scale×inW)]. I think this will waste some computation resources.

I'll appreciate it greatly if you can answer my question

**Comment by XuecaiHu** [comment]
Good question!! 
If we provide  mask.mat for the forward function,  maybe it can avoid this problems. I will spend some time to test the time study.
And thank your for my advice.

**Comment by suke27** [comment]
@yfzcopy0702 my 1st idea is do like  what you said, but it will slower than XuecaiHu's version. because mask will do in inchannels(maybe 64) but not 3 channels

**Comment by HymEric** [comment]
@yfzcopy0702 I have same question. And do you know why there is a *mask*? When I first read the paper, it doesn't appear in paper.

**Comment by ZhangDY827** [comment]
@HymEric  Actually, the model super-resolves the LR inputs with integer upscaling factors， due to the mask, the model is capable of solving super-resolution of arbitrary scale factor (including noninteger scale factors) with a single model.

**Comment by XuecaiHu** [comment]
@ZhangDY827  guy, your statement is false.  We use the mask to implement the meta-upscale module with Matrix operations instead of using "for" loop in python.

**Comment by ZhangDY827** [comment]
@XuecaiHu Hello, I have reproduced your paper recently and thanks for your great work firstly! In your metardn.py file,  you use "scale_int = math.ceil(self.scale)" to transfer the non-integer upscaling factor to integer factor. So, in my opinion, the size of output HR image is the integral. The mask matrix contains 0 and 1 to sample the useful pixel through "torch.masked_select" function.   Is my understanding correct?

**Comment by XuecaiHu** [comment]
@ZhangDY827  Maybe you should try to  implement the meta-upscale module yourself. And you will understand why i use the mask.   We add the unmeaning pixels which make the upscaled feature maps  suitable for matrix operations. And use the mask to remove the unmeaning pixels to generate the needed SR image. While, if you use two "for" loops to implement our meta-upscale layer as the Pseudo code in our paper, you donot need the mask but it is very time-consuming. It is the implementation details and it is unneccesary to introduce in our paper.
