### ISSUE TITLE
Can you expalin the mask_mat fuction in detail?

### ISSUE THREAD

**Issue by HymEric** [XuecaiHu/Meta-SR-Pytorch#20]
Can you expalin the mask_mat fuction in detail? I couldn't understand why there is a mask_mat.....

**Comment by wanghxcis** [comment]
I guess the mask_mat is used for training acceleration . So for the most scales, the program doesn't need to reallocate new memory.

**Comment by HymEric** [comment]
@wanghxcis 
Thank you. I guessed it is simple to use in inference stage for random scale just for one time training with multiple scales previously.
