### ISSUE TITLE
 Can it support in Windows10 + pytorch1.2? THX!

### ISSUE THREAD

**Issue by QQ2737499951** [XuecaiHu/Meta-SR-Pytorch#22]
Can it support in Windows10 + pytorch1.2? THX!

**Comment by XuecaiHu** [comment]
it can not support the pytorch 1.2, maybe you should change the dataloader.py

**Comment by ZhangDY827** [comment]
How can I change the dataloader.py ? I meet the problem when run the code. "AttributeError: '_MSDataLoaderIter' object has no attribute 'pin_memory_thread'".  The version of my pytorch is 1.0.0.

**Comment by tetterl** [comment]
https://github.com/tetterl/Meta-SR-Pytorch makes the dataloader compatible with 1.1.0 I think it will also work for 1.2.0
