### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by longlongvip** [XuecaiHu/Meta-SR-Pytorch#3]
hello Xuecai Hu,I have some question to ask.The following questions are
1.
What should I do with that part of the dataset? 
2.
Which dataset did you use? I have all the datasets
3.
What should I do with the **folder format of the dataset**？

**Comment by XuecaiHu** [comment]
1.You only need to run our matlab file to generate the training dataset and test dataset.
you should  change the path_save(which path do you to save ) and path_src (what is the path of  the HR image ).

2.In our paper, we only use the DIV2K training dataset as our training dataset.

3.  our matlab code will automaticly generate the folder format of the dataset which is suitable for our code.

Ps: my first name is Xuecai, Last name is Hu.
Good luck to you

**Comment by longlongvip** [comment]
Oh,I know it .I am sorry,I think I was confused.

**Comment by PSZehnder** [comment]
@XuecaiHu Can you make it more clear in the README how the data set file structure should be? Perhaps with an example folder tree? It took me a lot of time reading through the source code to figure out the correct structure.
