### ISSUE TITLE
Is the data wrong?

### ISSUE THREAD

**Issue by splinter21** [XuecaiHu/Meta-SR-Pytorch#33]
![3333](https://user-images.githubusercontent.com/26759495/69790893-4aa64f00-11fe-11ea-8f21-3c06663749b7.png)

**Comment by splinter21** [comment]
![444](https://user-images.githubusercontent.com/26759495/69793093-c4d8d280-1202-11ea-83f9-0e18cea0dbec.png)

barbara
前两个红圈PSNR和SSIM表现不一致
以及，为什么后4张，SSIM相差这么大？
img042
RDNx2和x4一样都是post-downscaling，x2居然会输了x4，很意外，为什么。。
另外，第三个红圈，RDNx2的PSNR这么糟糕，但是SSIM确实最大的，为什么？

**Comment by XuecaiHu** [comment]
Sorry for the late reply.  I will check the data again and fix the errors.
