### ISSUE TITLE
How to continue training from interrupted epochs

### ISSUE THREAD

**Issue by robinaman** [XuecaiHu/Meta-SR-Pytorch#34]
"--load"  can't running correctly

Prompt：No such file or directory: 'psnr_log.pt'

**Comment by XuecaiHu** [comment]
please use --pre_train      and --start_epoch,  --pre_train get   the model which you want to load,
 and --start_epoch  get the starting epoch.

**Comment by robinaman** [comment]
thanks for  your reply

**Comment by robinaman** [comment]
> "--load" can't running correctly
> 
> Prompt：No such file or directory: 'psnr_log.pt'
