### ISSUE TITLE
about the meaning of get_model function

### ISSUE THREAD

**Issue by ZiaZhang** [XuecaiHu/Meta-SR-Pytorch#38]
Hello, I don't figure out get_model(self) function in model/_init_.py, and can you explain what does "self.model.module" mean? Because I didn't find that the Class metardn (self.model) have the module function. Looking forward to your reply and thanks!

**Comment by XuecaiHu** [comment]
we use self.model.module to load the model when we use the multi-gpus to run the models. It is a function in pytorch. I donot redefine it.
