### ISSUE TITLE
about the last commit

### ISSUE THREAD

**Issue by xkeys** [XuecaiHu/Meta-SR-Pytorch#39]
Before the last commit, I can run the code well. Both demo and DIV2K. But when I cloned the code after change 2 weeks ago, there has an erro about the part of the code that lastly changed.
Belows are details.

$ python main.py --model metardn --ext sep  --save metardn --lr_decay 200 --epochs 1000 --n_GPUs 1 --batch_size 1
[1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0]
1
./benchmark/Set5/HR
./benchmark/Set5/LR_bicubic
5
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=844 error=11 : invalid argument
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    t.train()
  File "/home/xkey/dml/Meta-SR-Pytorch/trainer.py", line 143, in train
    scale_coord_map, mask = self.input_matrix_wpn_new(H,W,self.args.scale[idx_scale])  ###  get the position matrix, mask
  File "/home/xkey/dml/Meta-SR-Pytorch/trainer.py", line 106, in input_matrix_wpn_new
    while(pos_mat[i][0][0]!=0):
IndexError: index 200 is out of bounds for dimension 0 with size 200

Is there something wrong about my option?
Waiting for your reply!

**Comment by XuecaiHu** [comment]
yes,  it is a bug. I am trying to fix it right now.

**Comment by XuecaiHu** [comment]
不知道英文怎么说。bug的原因是由于精度问题，矩阵里的零都不是绝对零。所以导致找不到，从而越界。

**Comment by CYL0089** [comment]
请问这个问题解决了吗？～按照另一个评论的方法（如下所示）也没解决
change
h_project_coord = torch.arange(0,outH, 1).mul(1.0/scale).float()
to
h_project_coord = torch.arange(0,outH, 1).float().mul(1.0/scale)
