### ISSUE TITLE
question about the bug of Location Projection in trainer.py

### ISSUE THREAD

**Issue by Lixueqingqq** [XuecaiHu/Meta-SR-Pytorch#4]
Hellow XuecaiHu,
I'm trying to run the test demo,when I run the code , an error occured:
`python main.py --model metardn --save metardn --ext sep --pre_train ./experiment/metardn/model/model_1000.pt --test_only --data_test Set5  --scale 4 --n_GPUs 1`

the error information is:
`File "main.py", line 18, in <module>
    while not t.terminate():

  File "/Meta-SR-Pytorch-master/trainer.py", line 270, in terminate
    self.test()

  File "/Meta-SR-Pytorch-master/trainer.py", line 210, in test
    scale_coord_map, mask = self.input_matrix_wpn(H,W,self.args.scale[idx_scale])

  File "/Meta-SR-Pytorch-master/trainer.py", line 76, in input_matrix_wpn
    h_offset[int_h_project_coord[i], flag, 0] = offset_h_coord[i]
IndexError: index 4 is out of bounds for dimension 0 with size 4
`
Looking forward to your reply, thank you very much

**Comment by XuecaiHu** [comment]
the problem seems to be caused by the floor operation? Maybe int(4.0)==5. Since I can not reproduce this problem, i do not know the true the problem.
So, it is very helpful if you provide more information about the python version.

**Comment by Lixueqingqq** [comment]
Thank you for your answer.
my torch_version is 1.0.1,  python version is 3.5  and in my python int(4.0)==4
I printed the shape of variable:
h_project_coord_shape: torch.Size([512])
h_offset_shape: torch.Size([128, 4, 1])
offset_h_coord_shape: torch.Size([512])

**Comment by XuecaiHu** [comment]
check the int_project_coord matrix. maybe the torch.floor(h_project_coord)
or int_h_project_coord = int_h_project_coord.int()

some pixels  apear 5 times(which will cause the index out problem).

**Comment by Lixueqingqq** [comment]
thanks, I know the problem.
It is the fault of tensor.mul(). I find that in my torch version 'torch.arange(0,outH, 1).mul(1.0/scale)=0'
change
`h_project_coord = torch.arange(0,outH, 1).mul(1.0/scale).float()`
to
`h_project_coord = torch.arange(0,outH, 1).float().mul(1.0/scale)`
It is ok
