### ISSUE TITLE
RuntimeError: "floor" not implemented for 'torch.LongTensor'如何解决

### ISSUE THREAD

**Issue by mdswyz** [XuecaiHu/Meta-SR-Pytorch#44]

**Comment by Wjppppp** [comment]
I have the same problem with you, did you solve it?

**Comment by yooken233** [comment]
> I have the same problem with you, did you solve it?

I got this problem, too. did you solve it bro?

**Comment by yooken233** [comment]
> I have the same problem with you, did you solve it?
> 
> I got this problem, too. did you solve it bro?

Oh i think i have solved it. 
Use torch.arange(0., outH, 1.).mul(1.0 / scale)  instead of  torch.arange(0, outH, 1).mul(1.0 / scale).

**Comment by BlackGuang** [comment]
from
 h_project_coord = torch.arange(0, outH, 1).mul(1.0 / scale)
 to
 h_project_coord = torch.arange(0., outH, 1.).mul(1.0 / scale)
I have solved it too. Just  like yooken233
I have this idea from https://stackoverflow.com/questions/52922445/runtimeerror-exp-not-implemented-for-torch-longtensor
