### ISSUE TITLE
What does the parameter N mean?

### ISSUE THREAD

**Issue by astro-fits** [XuecaiHu/Meta-SR-Pytorch#45]
Hi Xuecai,

        I have a question about the parameter _N_  in Fig. 1 in your paper,  which is also illustrated in the follow figure. Would you mind telling me the meaning of the _N_  ?   Thank you very much !

![QQ图片20200224033318](https://user-images.githubusercontent.com/56294219/75127995-f9becd80-56fc-11ea-812c-3f5d654a5db4.png)

**Comment by astro-fits** [comment]
![QQ图片20200224033318](https://user-images.githubusercontent.com/56294219/75128269-3d660700-56fe-11ea-8d23-7bc73bfbf3a0.png)

attached figure

**Comment by XuecaiHu** [comment]
N is batchsize
