### ISSUE TITLE
数据预处理里面

### ISSUE THREAD

**Issue by djy-tsinghua** [XuecaiHu/Meta-SR-Pytorch#48]
if mod(h,scale) ~= 0
    h = h - 4;
end
请问这么做的原因是什么？h减去4也不能保证就被scale整除啊

**Comment by XuecaiHu** [comment]
这是因为matlab下采样是采用上取整的，即图片是h=3.4,实际生成图片为h=4，是为了防止测试时放大以后，sr图像会大于hr，我觉得这是不合理的，所以在构造下采样图片时，适当crop一些。至于是h=h-k. k的取值比较随意。保证整个实验设置一致即可。
