### ISSUE TITLE
need downscale labels when testing?/测试的时候需要相对应的下采样标签吗？

### ISSUE THREAD

**Issue by Darrenxc** [XuecaiHu/Meta-SR-Pytorch#49]
您好，请问一下当测试的时候，需要提供相应倍数的下采样标签，才能测试吗？
Do I need corresponding down-scale labels for testing?
Can I directly test my data without these labels, just the test images as the only one input?

thank you

**Comment by XuecaiHu** [comment]
必须有上采样的倍数
