### ISSUE TITLE
想请问meta.py代码的问题

### ISSUE THREAD

**Issue by Rainyliuliu** [XuecaiHu/Meta-SR-Pytorch#50]
想请问您代码上的一些问题。您论文里的meta.py网络结构，具体结构为什么会有两个分支，进行了不同的操作，我看好像是一个是投影后权重预测，一个是直接投影？这样做的原理是什么呢？在最后concate的目的又是什么呢？

**Comment by XuecaiHu** [comment]
meta.py的代码是参考CoordinateNet,将偏移量(投影计算得到)当成feature map跟原始图像的feature maps 进行合并一起训练。也是一种实现任意缩放倍数的方法。不过性能不行，故而文章里没提及。我己经将meta.py 改名为CoordiSR.py。
