### ISSUE TITLE
The shape of hr and sr is different when calculating psnr or ssim?

### ISSUE THREAD

**Issue by reddandelion217** [XuecaiHu/Meta-SR-Pytorch#51]
when testing, I met the problem as calculating psnr or ssim, I downloaded the test dataset from other website rather than the author provided because the baiduyunpai's link is not work and I can't visit Google Driver, so , Did any one meet the same problem with me?

**Comment by XuecaiHu** [comment]
To solve this problem, you should crop the hr[:,0:h_sr,0:w_sr]， Thus, hr and sr have the same size.
