### ISSUE TITLE
any one have the bug: RuntimeError: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by Peterisfar** [XuecaiHu/Meta-SR-Pytorch#6]
![image](https://user-images.githubusercontent.com/31852119/59144025-fca94f00-8a03-11e9-826a-61bad94482c6.png)

**Comment by XuecaiHu** [comment]
Can you tell me the version of your pytorch？

**Comment by Peterisfar** [comment]
> Can you tell me the version of your pytorch？

pytorch is 0.4.0, but cudnn is 10.0 , so error is resulted by cudnn
