### ISSUE TITLE
Meta-upscale的实现

### ISSUE THREAD

**Issue by xjhcassy** [XuecaiHu/Meta-SR-Pytorch#68]
你这Meta-upscale的实现跟论文不一致啊，代码是先整数上采样，再用Mask取对应的小数尺度的结果，跟论文中直接上采样到小数尺度的过程对不上？？ @XuecaiHu

**Comment by 924544296** [comment]
我也这么觉得啊，论文里提都没提。。。

**Comment by Hunter-Murphy** [comment]
没整明白，论文里面好多细节没提到

**Comment by Hunter-Murphy** [comment]
> 你这Meta-upscale的实现跟论文不一致啊，代码是先整数上采样，再用Mask取对应的小数尺度的结果，跟论文中直接上采样到小数尺度的过程对不上？？ @XuecaiHu
大佬能交流一下上采样模块的代码具体实现吗，想请教几个问题

**Comment by XuecaiHu** [comment]
这里是因为基于pytorch的卷积实现的，为了使用矩阵操作加速才增加了某些不需要预测的点，只是实现的问题，当然可以使用c++加cuda自己实现一个对内存更友好的版本，但是如何优化这部分代码对我来说是相对比较困难了。您理解为先上采样整数倍数，怕是对算法有什么误解。算法本质与文章描述就是一致的。
