### ISSUE TITLE
about training dataset

### ISSUE THREAD

**Issue by suke27** [XuecaiHu/Meta-SR-Pytorch#8]
hello, I have a problem about training dataset, as you said, you have .m to generate training dataset. seems your HR image just include on folder. is it possible make pair for 1.1 to 4.0 just using DIV2K default HR images? they may not a pair, like 2040 can not exact division by 1.9 1.8

**Comment by XuecaiHu** [comment]
Maybe different  scale factors have different sizes of the SR images. But all these images are smaller than the HR images.  Thus, the pair is (SR,HR(0:h_sr, 0:w_sr,:)), not (SR,HR)

**Comment by suke27** [comment]
during training, you need train multi scale at same time, as I try in my side, different scale will interacted on each other. some scale may get best psnr, Meanwhile, some get worse psnr . do you face this problem?

**Comment by XuecaiHu** [comment]
no, never
