### ISSUE TITLE
test dataset link not working

### ISSUE THREAD

**Issue by pancakewaffles** [XuecaiHu/Meta-SR-Pytorch#9]
Hi I tried to download the test dataset from the pan.baidu link but it wasn't working. I think it is saying something about file not found.

**Comment by suke27** [comment]
•download the dataset DIV2K and test dataset fetch code: hg69
that is invalid

**Comment by XuecaiHu** [comment]
I have update the gooledrive link and the baiduyun Link

**Comment by Leon924** [comment]
> I have update the gooledrive link and the baiduyun Link

The test dataset link doesnt work again, please check?
